# -*- coding: utf-8 -*-
"""Copy of Lab 9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14UMd0k-W55yURib6zmfBwHjp8odAnFok
"""

import torch
#Imports the PyTorch library, enabling the use of its functions and classes in the code.
from torchvision import datasets, transforms
#Imports specific modules (datasets and transforms) from the torchvision package. datasets contains pre-built datasets like MNIST, and transforms provides functions for data preprocessing.
import numpy as np
#Imports the NumPy library and assigns it the alias np. NumPy is commonly used for numerical computations in Python.

# Define a transform to normalize the data
transform = transforms.Compose([transforms.ToTensor()])
# Defines a data transformation pipeline using transforms.Compose. In this case, it consists of a single transformation, transforms.ToTensor(), which converts PIL images or numpy arrays into PyTorch tensors.

# Download and load the MNIST training data
train_data = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
#Downloads and loads the MNIST training dataset using the datasets.MNIST class. It specifies the root directory to save the data (./data), sets train=True to load the training set, download=True to download the dataset if it's not already available locally, and applies the previously defined transformation (transform=transform).

# Extracting the data and targets as tensors
train_images = train_data.data
#Extracts the images from the MNIST training dataset and assigns them to the variable train_images. The images are stored as torch tensors.
train_labels = train_data.targets
#Extracts the corresponding labels (targets) from the MNIST training dataset and assigns them to the variable train_labels. The labels are also stored as torch tensors.
train_images.shape, train_labels.shape
#Outputs the shapes of the train_images tensor and the train_labels tensor, respectively, providing information about the dimensions of the data.

#In summary, this code downloads the MNIST dataset, consisting of handwritten digit images and their corresponding labels, and prepares them for training a machine learning model by converting them into PyTorch tensors.

import matplotlib.pyplot as plt #imports library

28*28 #product: The significance of "28*28" lies in its association with the MNIST dataset, where each image is represented as a 28x28 grid of pixels. This size, 28x28, defines the dimensions of each image in the dataset. In machine learning tasks using MNIST, this size is crucial for tasks such as data preprocessing, model input shape specification, and understanding the complexity of the dataset.

train_images[0,:,:] #This line selects the first image from the train_images tensor along the first dimension (index 0), returning all rows and columns of the image.

x = train_images[0,:,:] #This line selects the first image from the `train_images` tensor and assigns it to a variable

plt.imshow(x) #`plt.imshow(x)` displays the image represented by the numpy array or tensor `x` using Matplotlib.

train_labels[0] #It accesses the first label in the `train_labels` tensor.

x.shape #Returns the shape (dimensions) of tensor \( x \).

x.flatten() #This line flattens the tensor `x`, converting it from a multi-dimensional array to a one-dimensional array.

x = x.flatten() #assigns to a variable

x.shape #This retrieves the shape of the tensor `x`, providing information about its dimensions.

x = x.reshape(28,28) #This reshapes the tensor `x` into a 28x28 matrix.

x.shape #gives dimensions

m = torch.rand(10,784) #This creates a PyTorch tensor `m` of size 10x784 filled with random numbers sampled from a uniform distribution between 0 and 1.

m #displays

m.shape #This retrieves the shape of the tensor `m`, indicating it has 10 rows and 784 columns.

x = x.flatten() #This line flattens the tensor `x`, converting it from a multi-dimensional array to a one-dimensional array.

x = x/255.0 #This line scales the values of tensor `x` to a range between 0 and 1 by dividing each element by 255.0.

x #displays new tensor

m.shape,x.shape #gives tensor dimensions

m@x #This performs matrix multiplication between tensors `m` and `x`.

y = torch.matmul(m,x) #This computes the matrix multiplication of tensors `m` and `x`, resulting in tensor `y`.

y #displays tensor y

torch.max(y) #This returns the maximum value contained within tensor `y`.

torch.argmax(y) #This returns the index of the maximum value in tensor `y`.

x = train_images[0:25,:,:]/255.0 #This line scales and selects the first 25 images from the MNIST training dataset, converting their pixel values to a range between 0 and 1.

x.shape #This retrieves the shape of the tensor `x`, indicating it contains 25 images with dimensions 28x28 each.

x = x.reshape(25,784) #This reshapes the tensor `x` into a 2D tensor with 25 rows and 784 columns, essentially flattening each image into a single row.

x.shape #gives tensor dimensions

x  = x.T #This line transposes the tensor `x`, swapping its dimensions.

x.shape #gives tensor dimensions

y = m@x #This line computes the matrix multiplication of tensors `m` and `x`, resulting in tensor `y`.

y.shape #This retrieves the shape of the tensor `y`, indicating its dimensions.

plt.imshow(y) #This line displays the image represented by tensor `y` using matplotlib's imshow function.

